[{"client_msg_id":"f6ecc013-282a-43da-8451-ef8add278817","type":"message","text":"Hi folks, I have a question about Julia code executing sequence. I have a function “func” that consists of 3 functions. func1 creates a file; func2 modifies the file; func3 processes the file. If I call 3 functions sequentially in Julia REPL, it works fine. However, when I call “func” in Julia, it pops an error, which looks like func3 was called before func2 was finished.  How comes this happen? Any comments are appreciated.","user":"U014ABSBL3A","ts":"1613764892.295500","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"hK5fF","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Hi folks, I have a question about Julia code executing sequence. I have a function “func” that consists of 3 functions. func1 creates a file; func2 modifies the file; func3 processes the file. If I call 3 functions sequentially in Julia REPL, it works fine. However, when I call “func” in Julia, it pops an error, which looks like func3 was called before func2 was finished.  How comes this happen? Any comments are appreciated."}]}]}],"thread_ts":"1613764892.295500","reply_count":3,"reply_users_count":3,"latest_reply":"1613765637.296100","reply_users":["UH24GRBLL","U014ABSBL3A","U8D9768Q6"],"subscribed":false},{"client_msg_id":"67aaf5df-ea03-4a81-a37f-07d969e8ece5","type":"message","text":"Are you sure func2 finished execution? Have you flushed all accesses to the opened file/closed the file?","user":"UH24GRBLL","ts":"1613765451.295600","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"6lOj","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Are you sure func2 finished execution? Have you flushed all accesses to the opened file/closed the file?"}]}]}],"thread_ts":"1613764892.295500","parent_user_id":"U014ABSBL3A","reactions":[{"name":"+1","users":["U8D9768Q6"],"count":1}]},{"client_msg_id":"14a2456b-216f-4984-b387-f05b28c6e08e","type":"message","text":"Good question! I’m not 100% sure (newbie here). But if I call the functions one by one and it works fine, I assume the files have been closed/flushed, right?","user":"U014ABSBL3A","ts":"1613765567.295900","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"U3T","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Good question! I’m not 100% sure (newbie here). But if I call the functions one by one and it works fine, I assume the files have been closed/flushed, right?"}]}]}],"thread_ts":"1613764892.295500","parent_user_id":"U014ABSBL3A"},{"client_msg_id":"76c30837-5745-4540-a615-52eef8fe9e30","type":"message","text":"I think probably runnuing them one by one induces enough latency that `func2` finishes before `funn3` starts. Probably something is happening asynchronously and needs to be locked.","user":"U8D9768Q6","ts":"1613765637.296100","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"Bog","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"I think probably runnuing them one by one induces enough latency that "},{"type":"text","text":"func2","style":{"code":true}},{"type":"text","text":" finishes before "},{"type":"text","text":"funn3","style":{"code":true}},{"type":"text","text":" starts. Probably something is happening asynchronously and needs to be locked."}]}]}],"thread_ts":"1613764892.295500","parent_user_id":"U014ABSBL3A"}]