[{"client_msg_id":"ef958ea3-a029-4906-a4c2-4c2359f28864","type":"message","text":"Does anybody know why the following code generates an illegal memory access error (code 700, ERROR_ILLEGAL_ADDRESS)? I restarted Julia and just ran the following.\n```using CUDA\n\nfunction kernel(n::Int, arr::CuDeviceArray{Float64})\n    x = @cuDynamicSharedMem(Float64, n)\n    xl = @cuDynamicSharedMem(Float64, n, n*sizeof(Float64))\n\n    I = blockIdx().x\n\n    xl[5] = arr[I]\n    xl[6] = arr[I]\n    CUDA.sync_threads()\n\n    return\nend\n\nn = 8\nnblk = 9\narr = CuArray{Float64}(undef, nblk)\ncopyto!(arr, ones(nblk))\n\nCUDA.@sync @cuda threads=32 blocks=nblk shmem=((2*n)*sizeof(Float64)) kernel(n,arr)```\nI'm using Julia 1.5.2 and CUDA.jl 2.3.0.","user":"U01FXSDEXN3","ts":"1613057505.161700","team":"T68168MUP","edited":{"user":"U01FXSDEXN3","ts":"1613058140.000000"},"blocks":[{"type":"rich_text","block_id":"ugg","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Does anybody know why the following code generates an illegal memory access error (code 700, ERROR_ILLEGAL_ADDRESS)? I restarted Julia and just ran the following.\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"using CUDA\n\nfunction kernel(n::Int, arr::CuDeviceArray{Float64})\n    x = @cuDynamicSharedMem(Float64, n)\n    xl = @cuDynamicSharedMem(Float64, n, n*sizeof(Float64))\n\n    I = blockIdx().x\n\n    xl[5] = arr[I]\n    xl[6] = arr[I]\n    CUDA.sync_threads()\n\n    return\nend\n\nn = 8\nnblk = 9\narr = CuArray{Float64}(undef, nblk)\ncopyto!(arr, ones(nblk))\n\nCUDA.@sync @cuda threads=32 blocks=nblk shmem=((2*n)*sizeof(Float64)) kernel(n,arr)"}]},{"type":"rich_text_section","elements":[{"type":"text","text":"I'm using Julia 1.5.2 and CUDA.jl 2.3.0."}]}]}],"thread_ts":"1613057505.161700","reply_count":8,"reply_users_count":2,"latest_reply":"1613059785.163700","reply_users":["U68A3ASP9","U01FXSDEXN3"],"subscribed":false},{"client_msg_id":"15e64de7-50f5-4fc4-a98a-b93f57fdd04e","type":"message","text":"works here without errors","user":"U68A3ASP9","ts":"1613058435.162300","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"zGuMy","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"works here without errors"}]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"},{"client_msg_id":"75fe414a-6184-4426-a08e-43a050e46446","type":"message","text":"Thanks a lot for checking. Do you think I might have to restart the computer? Not sure what to do in this case. By the way, the error messages were\n```ERROR: LoadError: CUDA error: an illegal memory access was encountered (code 700, ERROR_ILLEGAL_ADDRESS)\nStacktrace:\n [1] throw_api_error(::CUDA.cudaError_enum) at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/cudadrv/error.jl:97\n [2] macro expansion at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/cudadrv/error.jl:104 [inlined]\n [3] cuEventSynchronize at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/utils/call.jl:93 [inlined]\n [4] synchronize(::CuEvent) at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/cudadrv/events.jl:52\n [5] top-level scope at /home/youngdae/.julia/packages/CUDA/YeS8q/src/utilities.jl:37\n [6] include(::String) at ./client.jl:457\n [7] top-level scope at REPL[1]:1\nin expression starting at /home/youngdae/git-repos/admm/src/test.jl:21```\nand when I exit Julia it also gives me the following errors:\n```error in running finalizer: CUDA.CuError(code=CUDA.cudaError_enum(0x000002bc), meta=nothing)\nerror in running finalizer: CUDA.CuError(code=CUDA.cudaError_enum(0x000002bc), meta=nothing)```\n","user":"U01FXSDEXN3","ts":"1613058768.162500","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"eJF","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Thanks a lot for checking. Do you think I might have to restart the computer? Not sure what to do in this case. By the way, the error messages were\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"ERROR: LoadError: CUDA error: an illegal memory access was encountered (code 700, ERROR_ILLEGAL_ADDRESS)\nStacktrace:\n [1] throw_api_error(::CUDA.cudaError_enum) at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/cudadrv/error.jl:97\n [2] macro expansion at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/cudadrv/error.jl:104 [inlined]\n [3] cuEventSynchronize at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/utils/call.jl:93 [inlined]\n [4] synchronize(::CuEvent) at /home/youngdae/.julia/packages/CUDA/YeS8q/lib/cudadrv/events.jl:52\n [5] top-level scope at /home/youngdae/.julia/packages/CUDA/YeS8q/src/utilities.jl:37\n [6] include(::String) at ./client.jl:457\n [7] top-level scope at REPL[1]:1\nin expression starting at /home/youngdae/git-repos/admm/src/test.jl:21"}]},{"type":"rich_text_section","elements":[{"type":"text","text":"and when I exit Julia it also gives me the following errors:\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"error in running finalizer: CUDA.CuError(code=CUDA.cudaError_enum(0x000002bc), meta=nothing)\nerror in running finalizer: CUDA.CuError(code=CUDA.cudaError_enum(0x000002bc), meta=nothing)"}]},{"type":"rich_text_section","elements":[]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"},{"client_msg_id":"943c3942-2b56-4984-a378-4902d010f785","type":"message","text":"reboot shouldn't help here","user":"U68A3ASP9","ts":"1613058940.162700","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"u3l","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"reboot shouldn't help here"}]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"},{"client_msg_id":"584db0e9-4d89-45dc-ac10-e60998fad528","type":"message","text":"try running under `cuda-memcheck`","user":"U68A3ASP9","ts":"1613058950.162900","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"VKeTf","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"try running under "},{"type":"text","text":"cuda-memcheck","style":{"code":true}}]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"},{"client_msg_id":"b606f825-9ed0-4978-8539-bb7351e59790","type":"message","text":"It threw a bunch of error messages, but they were all the same errors occurred when writing to the shared memory by threads of each block:\n```========= Invalid __shared__ write of size 8\n=========     at 0x00000250 in julia_kernel_2095(Int64, CuDeviceArray&lt;Float64, int=1, int=1&gt;)\n=========     by thread (31,0,0) in block (8,0,0)\n=========     Address 0x32000068 is out of bounds\n=========     Device Frame:julia_kernel_2095(Int64, CuDeviceArray&lt;Float64, int=1, int=1&gt;) (julia_kernel_2095(Int64, CuDeviceArray&lt;Float64, int=1, int=1&gt;) : 0x250)\n=========     Saved host backtrace up to driver entry point at kernel launch time```","user":"U01FXSDEXN3","ts":"1613059394.163100","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"fFSt","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"It threw a bunch of error messages, but they were all the same errors occurred when writing to the shared memory by threads of each block:\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"========= Invalid __shared__ write of size 8\n=========     at 0x00000250 in julia_kernel_2095(Int64, CuDeviceArray<Float64, int=1, int=1>)\n=========     by thread (31,0,0) in block (8,0,0)\n=========     Address 0x32000068 is out of bounds\n=========     Device Frame:julia_kernel_2095(Int64, CuDeviceArray<Float64, int=1, int=1>) (julia_kernel_2095(Int64, CuDeviceArray<Float64, int=1, int=1>) : 0x250)\n=========     Saved host backtrace up to driver entry point at kernel launch time"}]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"},{"client_msg_id":"641ec8f3-1146-4491-a7ac-42e7e036b037","type":"message","text":"Is there a way to see where the shared memory was allocated? I would like to verify if the address 0x32000068 is within range or not.","user":"U01FXSDEXN3","ts":"1613059509.163300","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"PZ1A","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Is there a way to see where the shared memory was allocated? I would like to verify if the address 0x32000068 is within range or not."}]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"},{"client_msg_id":"fd6c6f05-554d-4bf2-bdf8-2d832d5652b8","type":"message","text":"you can `@cushow pointer(x)`","user":"U68A3ASP9","ts":"1613059763.163500","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"xijE","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"you can "},{"type":"text","text":"@cushow pointer(x)","style":{"code":true}}]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"},{"client_msg_id":"babac201-6fc6-47d4-aa4e-e92c3d2aa8e2","type":"message","text":"might have to reinterpret the pointer to a `Ptr`","user":"U68A3ASP9","ts":"1613059785.163700","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"2U1","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"might have to reinterpret the pointer to a "},{"type":"text","text":"Ptr","style":{"code":true}}]}]}],"thread_ts":"1613057505.161700","parent_user_id":"U01FXSDEXN3"}]