[{"client_msg_id":"6f921030-a7ed-466c-a222-65b16bea40de","type":"message","text":"```py\"\"\"\nimport skimage\nimport os \n \nfile = os.path.join(r\"C:\\Users\\DEBRAJ\\Downloads\", 'Screenshot (261).png') \n   \ndef testload():\n    cars = skimage.io.imread(file)\n    return cars\n\"\"\"```","user":"U01HWULJR2N","ts":"1611384066.188900","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"5dKeK","elements":[{"type":"rich_text_preformatted","elements":[{"type":"text","text":"py\"\"\"\nimport skimage\nimport os \n \nfile = os.path.join(r\"C:\\Users\\DEBRAJ\\Downloads\", 'Screenshot (261).png') \n   \ndef testload():\n    cars = skimage.io.imread(file)\n    return cars\n\"\"\""}]}]}],"thread_ts":"1611384066.188900","reply_count":8,"reply_users_count":2,"latest_reply":"1611395142.190500","reply_users":["U01HWULJR2N","U6NFPDBV1"],"subscribed":false},{"client_msg_id":"d616f4e1-d7a7-4136-87c8-9734c741e174","type":"message","text":"i get error following error for this code:\n```PyError ($(Expr(:escape, :(ccall(#= C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) &lt;class 'ModuleNotFoundError'&gt;\nModuleNotFoundError(\"No module named 'skimage'\")\n  File \"C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\pyeval.jl\", line 1, in &lt;module&gt;\n    const Py_single_input = 256  # from Python.h\n\n\nStacktrace:\n [1] pyerr_check at C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\exception.jl:62 [inlined]\n [2] pyerr_check at C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\exception.jl:66 [inlined]\n [3] _handle_error(::String) at C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\exception.jl:83```","user":"U01HWULJR2N","ts":"1611384147.189100","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"quj","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"i get error following error for this code:\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"PyError ($(Expr(:escape, :(ccall(#= C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'ModuleNotFoundError'>\nModuleNotFoundError(\"No module named 'skimage'\")\n  File \"C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\pyeval.jl\", line 1, in <module>\n    const Py_single_input = 256  # from Python.h\n\n\nStacktrace:\n [1] pyerr_check at C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\exception.jl:62 [inlined]\n [2] pyerr_check at C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\exception.jl:66 [inlined]\n [3] _handle_error(::String) at C:\\Users\\DEBRAJ\\.julia\\packages\\PyCall\\tqyST\\src\\exception.jl:83"}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"},{"client_msg_id":"a5554046-1ec6-4ab1-ac6f-be8fdf169239","type":"message","text":"Can someone help?","user":"U01HWULJR2N","ts":"1611384161.189300","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"iNf4","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Can someone help?"}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"},{"client_msg_id":"2cfe7d7d-f337-45be-97ea-ab69c87b0f16","type":"message","text":"Looks like your Python environment doesn't have skimage installed","user":"U6NFPDBV1","ts":"1611384829.189500","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"bmq","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Looks like your Python environment doesn't have skimage installed"}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"},{"client_msg_id":"e7448df8-5b2e-4097-a561-2a8c015e2804","type":"message","text":"it is installed and i can run it directly in python,but when i call in julia,it throws the error.","user":"U01HWULJR2N","ts":"1611385507.189700","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"hsz","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"it is installed and i can run it directly in python,but when i call in julia,it throws the error."}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"},{"client_msg_id":"cd96cf4a-6aae-4d18-9376-c95a717d8165","type":"message","text":"PyCall uses an isolated environment, see the docs","user":"U6NFPDBV1","ts":"1611388704.189900","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"u95kA","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"PyCall uses an isolated environment, see the docs"}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"},{"client_msg_id":"43e71550-56dd-4c33-8787-947c0f94595e","type":"message","text":"But then why it works fine for numpy?? Confused:sweat_smile:.","user":"U01HWULJR2N","ts":"1611390615.190100","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"kAu","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"But then why it works fine for numpy?? Confused"},{"type":"emoji","name":"sweat_smile"},{"type":"text","text":"."}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"},{"client_msg_id":"a40605e1-91bc-4649-ac46-ee976147c967","type":"message","text":"Pretty sure numpy is installed by default by conda","user":"U6NFPDBV1","ts":"1611392303.190300","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"6wZ85","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Pretty sure numpy is installed by default by conda"}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"},{"client_msg_id":"fd43e929-baf6-481f-acd5-3b7d6fd32c59","type":"message","text":"Oho, let me check, and which docs you referred to, the readme. md file i guess?","user":"U01HWULJR2N","ts":"1611395142.190500","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"OOiiL","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Oho, let me check, and which docs you referred to, the readme. md file i guess?"}]}]}],"thread_ts":"1611384066.188900","parent_user_id":"U01HWULJR2N"}]